// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at ١٤‏/٩‏/٢٠٢٥، ٥:٤٥:٢٦ م
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["H:/Code/Beingmomen/Daowud/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","H:/Code/Beingmomen/Daowud/client/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","H:/Code/Beingmomen/Daowud/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","H:/Code/Beingmomen/Daowud/client/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","H:/Code/Beingmomen/Daowud/client/plugins/**/*.{js,ts,mjs}","H:/Code/Beingmomen/Daowud/client/composables/**/*.{js,ts,mjs}","H:/Code/Beingmomen/Daowud/client/utils/**/*.{js,ts,mjs}","H:/Code/Beingmomen/Daowud/client/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","H:/Code/Beingmomen/Daowud/client/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","H:/Code/Beingmomen/Daowud/client/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","H:/Code/Beingmomen/Daowud/client/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;